# Generated by Django 5.0.7 on 2024-08-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train', models.CharField(max_length=50)),
                ('passenger', models.CharField(max_length=100)),
                ('state_depart', models.CharField(max_length=50)),
                ('state_arrive', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('carriage', models.IntegerField()),
                ('seat', models.CharField(blank=True, editable=False, max_length=50)),
                ('platform', models.CharField(blank=True, editable=False, max_length=50)),
            ],
        ),
    ]
